Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -11,15 +11,8 @@ phases:
       - PIPELINE_BRANCH=$(echo $TRIGGER_DETAIL | jq -r '.branchName')
       - echo "Pipeline branch is $PIPELINE_BRANCH"
       - FINAL_BRANCH_NAME=$PIPELINE_BRANCH
-      - |
-        if [[ "$FINAL_BRANCH_NAME" =~ ^dev-v[0-9]+\.[0-9]+$ ]]; then
-          export ECR_REPO_NAME=$AWS_UAT_REPO
-        elif [[ "$FINAL_BRANCH_NAME" =~ ^hotfix-v[0-9]+\.[0-9]+$ ]]; then
-          export ECR_REPO_NAME=$AWS_PREPROD_REPO
-        else
-          echo "Invalid branch: $FINAL_BRANCH_NAME"
-          exit 1
-        fi
+      - echo "Final branch name is $FINAL_BRANCH_NAME"
+      - 'if [[ "$FINAL_BRANCH_NAME" =~ ^dev-v[0-9]+\.[0-9]+$ ]]; then export ECR_REPO_NAME=$AWS_UAT_REPO; elif [[ "$FINAL_BRANCH_NAME" =~ ^hotfix-v[0-9]+\.[0-9]+$ ]]; then export ECR_REPO_NAME=$AWS_PREPROD_REPO; else echo "Invalid branch: $FINAL_BRANCH_NAME"; exit 1; fi'
       - export REPOSITORY_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME"
       - export IMAGE_REPO_NAME=$ECR_REPO_NAME
       - echo "Using repository $REPOSITORY_URI"
